# Data Workflow Lab 1

Clean and summarize Project 3 data.

### Learning Objectives

* Practice text cleaning techniques
* Practice datatype conversion
* Practice filling in missing values with either 0 or the average in the column
* Practice categorical data techniques
* Transform data into usable quantities

In [1]:
% matplotlib inline
import datetime
import numpy as np
import pandas as pd

In [4]:
pwd

u'/vagrant/DSI_JY/DSI-projects/classes/week-03/3.3-lab/code/starter-code'

In [7]:
# Load the data
df = pd.read_csv("../../../../../projects/project-03/Iowa_Liquor_sales_sample_10pct.csv")
print df.columns
df.head()

Index([u'Date', u'Store Number', u'City', u'Zip Code', u'County Number',
       u'County', u'Category', u'Category Name', u'Vendor Number',
       u'Item Number', u'Item Description', u'Bottle Volume (ml)',
       u'State Bottle Cost', u'State Bottle Retail', u'Bottles Sold',
       u'Sale (Dollars)', u'Volume Sold (Liters)', u'Volume Sold (Gallons)'],
      dtype='object')

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34
3,02/03/2016,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77
4,08/18/2015,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55

## Clean the data

Let's practice our data cleaning skills on the Project 3 dataset. If you don't remember how to do any of these tasks, look back at your work from the previous weeks or search the internet. There are many blog articles and Stack Overflow posts that cover these topics.

You'll want to complete at least the following tasks:
* Remove redundant columns
* Remove "$" prices from characters and convert values to floats.
* Convert dates to pandas datetime objects
* Convert category floats to integers
* Drop or fill in bad values

In [8]:
# Remove redundant columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270955 entries, 0 to 270954
Data columns (total 18 columns):
Date                     270955 non-null object
Store Number             270955 non-null int64
City                     270955 non-null object
Zip Code                 270955 non-null object
County Number            269878 non-null float64
County                   269878 non-null object
Category                 270887 non-null float64
Category Name            270323 non-null object
Vendor Number            270955 non-null int64
Item Number              270955 non-null int64
Item Description         270955 non-null object
Bottle Volume (ml)       270955 non-null int64
State Bottle Cost        270955 non-null object
State Bottle Retail      270955 non-null object
Bottles Sold             270955 non-null int64
Sale (Dollars)           270955 non-null object
Volume Sold (Liters)     270955 non-null float64
Volume Sold (Gallons)    270955 non-null float64
dtypes: float64(4), int64(5), object(9)
memory usage: 37.2+ MB

In [10]:
df['Item Description'].value_counts().count()

2173

In [13]:
df.drop('Volume Sold (Gallons)',axis=1, inplace = True)

In [14]:
df.isnull().sum()

Date                       0
Store Number               0
City                       0
Zip Code                   0
County Number           1077
County                  1077
Category                  68
Category Name            632
Vendor Number              0
Item Number                0
Item Description           0
Bottle Volume (ml)         0
State Bottle Cost          0
State Bottle Retail        0
Bottles Sold               0
Sale (Dollars)             0
Volume Sold (Liters)       0
dtype: int64

In [15]:
df['State Bottle Cost'] = df['State Bottle Cost'].str.replace('$','').astype(float)

In [17]:
df['State Bottle Retail'] = df['State Bottle Retail'].str.replace('$','').astype(float)

In [18]:
df['Sale (Dollars)'] = df['Sale (Dollars)'].str.replace('$','').astype(float)

In [20]:
df['Date'] = pd.to_datetime(df['Date'])

In [86]:
pd.pivot_table(df, columns = 'Store Number')[['County Number']].value_counts()

AttributeError: 'DataFrameGroupBy' object has no attribute 'value_counts'

In [22]:
df[df['County Number'].isnull()].sample(10)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
199501,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1012200.0,SCOTCH WHISKIES,55,8827,Lauder's,1000,6.14,9.21,3,27.63,3.00
249514,2016-03-09,2637,DAVENPORT,52804,NaN,NaN,1062300.0,FLAVORED RUM,370,43536,Malibu Pineapple Upside Down Cake,750,7.49,11.24,12,134.88,9.00
78668,2016-01-25,3591,ACKLEY,50601,NaN,NaN,1081015.0,IMPORTED AMARETTO,130,64136,Disaronno Amaretto,750,13.86,20.79,3,62.37,2.25
228451,2016-02-01,4222,EVANSDALE,50707,NaN,NaN,1062300.0,FLAVORED RUM,35,43136,Bacardi Limon,750,8.26,12.39,4,49.56,3.00
230854,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,260,25608,Seagrams 7 Crown Bl Whiskey,1750,11.96,17.94,6,107.64,10.50
155982,2016-03-15,3632,DUBUQUE,52003,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,260,69946,Rumple Minze Peppermint Schnapps Liqueur,750,13.00,19.50,12,234.00,9.00
27055,2016-02-16,5230,CEDAR RAPIDS,52402,NaN,NaN,1011300.0,TENNESSEE WHISKIES,85,26821,Jack Daniels Old #7 Black Lbl Mini,500,9.06,13.59,2,27.18,1.00
169878,2015-09-08,4247,BELMOND,50421,NaN,NaN,1011300.0,TENNESSEE WHISKIES,85,86670,Jack Daniel's Tennessee Honey,750,15.07,22.61,12,271.32,9.00
95655,2016-03-15,3632,DUBUQUE,52003,NaN,NaN,1022100.0,TEQUILA,395,89215,Jose Cuervo Tradicional Reposado Tequila,750,14.90,22.35,12,268.20,9.00
163578,2016-01-20,4308,CORALVILLE,52241,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35914,Five O'clock Vodka,375,1.93,2.90,24,69.60,9.00

In [ ]:
# Remove $ from certain columns

In [62]:
df[df['County Number'].isnull()]['Store Number'].value_counts()

4247    153
3820     83
5210     80
5230     65
2637     64
2460     64
5220     61
5236     49
3632     40
5222     33
4307     31
3682     28
5227     27
4222     23
2353     23
4203     23
2650     23
5224     20
4214     14
3591     14
5225     14
4308     13
4169     13
5226     13
5214     12
3747     11
2152     10
2238      9
5247      7
5240      7
4006      6
5217      6
5237      6
5229      5
5232      4
5233      4
5208      4
3826      4
5234      3
5223      3
5216      3
5218      2
Name: Store Number, dtype: int64

In [63]:
df[df['Store Number']==4247]

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
964,2015-05-19,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,55,12408,Canadian Ltd Whisky,1750,9.14,13.71,6,82.26,10.50
2871,2015-09-22,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,65,44428,Cruzan Blueberry Lemonade,750,6.83,10.25,1,10.25,0.75
4448,2015-03-03,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,380,37338,UV Vodka PET,1750,10.49,15.99,6,95.94,10.50
7834,2015-03-17,4247,BELMOND,50421,NaN,NaN,1071100.0,AMERICAN COCKTAILS,395,58838,Jose Cuervo Authentic Lime Margarita,1750,8.20,12.30,6,73.80,10.50
9790,2015-10-20,4247,BELMOND,50421,NaN,NaN,1012200.0,SCOTCH WHISKIES,260,10008,Scoresby Rare Scotch,1750,10.50,15.75,1,15.75,1.75
12422,2015-03-17,4247,BELMOND,50421,NaN,NaN,1081200.0,CREAM LIQUEURS,260,68036,Bailey's Original Irish Cream,750,13.25,19.88,3,59.64,2.25
13112,2015-08-04,4247,BELMOND,50421,NaN,NaN,1012200.0,SCOTCH WHISKIES,260,10008,Scoresby Rare Scotch,1750,10.50,15.75,2,31.50,3.50
13686,2016-02-23,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,434,36308,Hawkeye Vodka,1750,7.17,10.76,12,129.12,21.00
14529,2015-07-21,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,11298,Crown Royal Canadian Whisky,1750,31.99,47.99,6,287.94,10.50
16512,2015-03-17,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,55,12406,Canadian Ltd Whisky,750,3.84,6.01,12,72.12,9.00
19443,2015-12-04,4247,BELMOND,50421,99.0,Wright,1032200.0,IMPORTED VODKA - MISC,370,34026,Absolut Peppar,750,11.49,17.24,1,17.24,0.75
23084,2015-12-29,4247,BELMOND,50421,99.0,Wright,1012100.0,CANADIAN WHISKIES,115,11788,Black Velvet,1750,9.70,14.93,18,268.74,31.50
23110,2015-05-05,4247,BELMOND,50421,NaN,NaN,1081350.0,SPEARMINT SCHNAPPS,434,82187,Arrow Spearmint Schnapps,1000,5.00,7.50,2,15.00,2.00
24082,2015-07-14,4247,BELMOND,50421,NaN,NaN,1012200.0,SCOTCH WHISKIES,35,4866,Dewars White Label Scotch,750,13.73,20.60,2,41.20,1.50
26604,2016-03-22,4247,BELMOND,50421,NaN,NaN,1062310.0,SPICED RUM,260,43338,Captain Morgan Spiced Rum,1750,18.00,27.00,12,324.00,21.00
27256,2015-03-10,4247,BELMOND,50421,NaN,NaN,1071100.0,AMERICAN COCKTAILS,395,58875,Jose Cuervo Golden Margarita,1750,10.50,15.75,6,94.50,10.50
27547,2015-11-03,4247,BELMOND,50421,NaN,NaN,1022100.0,TEQUILA,395,89197,Jose Cuervo Especial Reposado Tequila,1000,12.50,18.75,1,18.75,1.00
27758,2016-01-05,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,370,42716,Malibu Coconut Rum,750,7.49,11.24,12,134.88,9.00
29819,2015-02-17,4247,BELMOND,50421,NaN,NaN,1062200.0,PUERTO RICO & VIRGIN ISLANDS RUM,434,45278,Paramount White Rum,1750,7.84,11.76,6,70.56,10.50
30141,2015-02-17,4247,BELMOND,50421,NaN,NaN,1071100.0,AMERICAN COCKTAILS,55,57144,Chi-Chi's White Russian,1750,6.50,9.75,6,58.50,10.50
31851,2015-09-15,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,35,43138,Bacardi Limon,1750,15.00,22.50,2,45.00,3.50
31930,2015-10-20,4247,BELMOND,50421,NaN,NaN,1081200.0,CREAM LIQUEURS,260,68036,Bailey's Original Irish Cream,750,13.25,19.88,2,39.76,1.50
32099,2015-08-11,4247,BELMOND,50421,NaN,NaN,1042100.0,IMPORTED DRY GINS,260,28868,Tanqueray Gin,1750,24.99,37.49,6,224.94,10.50
32540,2015-02-17,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,370,42703,Malibu Pineapple Rum,750,7.49,11.24,3,33.72,2.25
34547,2015-05-12,4247,BELMOND,50421,NaN,NaN,1031200.0,VODKA FLAVORED,260,77648,Smirnoff Citrus,1000,9.25,13.88,3,41.64,3.00
36506,2015-10-20,4247,BELMOND,50421,NaN,NaN,1081600.0,WHISKEY LIQUEUR,421,64868,Fireball Cinnamon Whiskey,1750,15.33,23.00,1,23.00,1.75
37416,2015-07-14,4247,BELMOND,50421,NaN,NaN,1042100.0,IMPORTED DRY GINS,260,28866,Tanqueray Gin,750,12.25,18.38,12,220.56,9.00
39498,2015-06-23,4247,BELMOND,50421,NaN,NaN,1032080.0,IMPORTED VODKA,65,34578,Pinnacle Vodka,1750,12.59,18.89,6,113.34,10.50
39499,2016-02-02,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,65,44419,Cruzan Black Cherry Rum,750,6.83,10.25,1,10.25,0.75
41806,2016-03-08,4247,BELMOND,50421,NaN,NaN,1062310.0,SPICED RUM,260,43338,Captain Morgan Spiced Rum,1750,18.00,27.00,6,162.00,10.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218031,2016-02-02,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,65,44456,Cruzan Raspberry Rum,750,6.83,10.25,2,20.50,1.50
220009,2016-02-09,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,65,10628,Canadian Club Whisky,1750,15.75,23.63,6,141.78,10.50
220722,2015-12-01,4247,BELMOND,50421,99.0,Wright,1012100.0,CANADIAN WHISKIES,55,12408,Canadian Ltd Whisky,1750,7.94,12.51,12,150.12,21.00
221210,2016-02-09,4247,BELMOND,50421,NaN,NaN,1031200.0,VODKA FLAVORED,260,77688,Smirnoff Lime,750,8.25,12.38,2,24.76,1.50
221749,2016-02-02,4247,BELMOND,50421,NaN,NaN,1062200.0,PUERTO RICO & VIRGIN ISLANDS RUM,35,43128,Bacardi Superior Rum,1750,15.00,22.50,6,135.00,10.50
225517,2016-02-16,4247,BELMOND,50421,NaN,NaN,1022100.0,TEQUILA,421,88766,Tortilla White Tequila,750,6.20,9.30,3,27.90,2.25
226288,2015-03-03,4247,BELMOND,50421,NaN,NaN,1012200.0,SCOTCH WHISKIES,35,4866,Dewars White Label Scotch,750,13.73,20.60,1,20.60,0.75
227326,2015-11-17,4247,BELMOND,50421,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,65,20248,Old Crow,1750,10.49,15.74,1,15.74,1.75
228545,2015-01-06,4247,BELMOND,50421,NaN,NaN,1032200.0,IMPORTED VODKA - MISC,370,34190,Absolut Cherrykran,750,11.49,17.24,1,17.24,0.75
230169,2015-06-23,4247,BELMOND,50421,NaN,NaN,1062200.0,PUERTO RICO & VIRGIN ISLANDS RUM,434,45246,Paramount Gold Rum,750,4.34,6.51,24,156.24,18.00
231428,2015-02-17,4247,BELMOND,50421,NaN,NaN,1031200.0,VODKA FLAVORED,260,77648,Smirnoff Citrus,1000,9.25,13.88,1,13.88,1.00
232148,2015-10-20,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,115,10550,Black Velvet Toasted Caramel,750,6.75,10.13,12,121.56,9.00
233261,2015-12-21,4247,BELMOND,50421,99.0,Wright,1071100.0,AMERICAN COCKTAILS,395,58838,Jose Cuervo Authentic Lime Margarita,1750,8.20,12.30,6,73.80,10.50
234443,2015-05-19,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35916,Five O'clock Vodka,750,3.37,5.06,12,60.72,9.00
235688,2015-09-29,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10807,Crown Royal Regal Apple,750,15.00,22.50,2,45.00,1.50
237344,2015-02-17,4247,BELMOND,50421,NaN,NaN,1071100.0,AMERICAN COCKTAILS,55,57148,Chi-Chi's Margarita W/tequila,1750,6.50,9.75,6,58.50,10.50
239262,2015-12-01,4247,BELMOND,50421,99.0,Wright,1071100.0,AMERICAN COCKTAILS,55,57148,Chi-Chi's Margarita W/tequila,1750,6.00,9.25,2,18.50,3.50
239729,2015-08-11,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,115,11776,Black Velvet,750,5.23,7.85,12,94.20,9.00
239926,2016-02-16,4247,BELMOND,50421,NaN,NaN,1031100.0,100 PROOF VODKA,297,35916,Five O'clock Vodka,750,3.37,5.06,12,60.72,9.00
243489,2015-02-17,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,260,37996,Smirnoff Vodka 80 Prf,750,8.25,12.38,12,148.56,9.00
251269,2016-03-15,4247,BELMOND,50421,NaN,NaN,1022100.0,TEQUILA,421,88768,Tortilla White Tequila,1750,12.64,18.96,1,18.96,1.75
252327,2015-01-13,4247,BELMOND,50421,NaN,NaN,1032080.0,IMPORTED VODKA,370,34007,Absolut Swedish Vodka 80 Prf,1000,14.99,22.49,1,22.49,1.00
253761,2015-08-11,4247,BELMOND,50421,NaN,NaN,1032200.0,IMPORTED VODKA - MISC,370,34116,Absolut Mandrin,750,11.49,17.24,1,17.24,0.75
255537,2015-08-04,4247,BELMOND,50421,NaN,NaN,1012200.0,SCOTCH WHISKIES,35,4866,Dewars White Label Scotch,750,13.73,20.60,1,20.60,0.75
258387,2015-05-19,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,7.20,10.80,6,64.80,10.50
262521,2015-10-13,4247,BELMOND,50421,NaN,NaN,1042100.0,IMPORTED DRY GINS,260,28868,Tanqueray Gin,1750,24.99,37.49,6,224.94,10.50
263934,2015-10-13,4247,BELMOND,50421,NaN,NaN,1081330.0,PEACH SCHNAPPS,65,82846,Dekuyper Luscious Peachtree Schnapps,750,6.30,9.45,2,18.90,1.50
266383,2015-09-08,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35916,Five O'clock Vodka,750,3.37,5.06,12,60.72,9.00
268504,2016-02-23,4247,BELMOND,50421,NaN,NaN,1062310.0,SPICED RUM,260,43418,Captain Morgan Tattoo,750,9.00,13.50,2,27.00,1.50
270031,2015-05-12,4247,BELMOND,50421,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,421,69667,Dr. Mcgillicuddy's Vanilla,1000,11.00,16.50,1,16.50,1.00

In [83]:
df_store_county_ref = pd.DataFrame(data=df['Store Number'].unique())
df_store_county_ref.columns = ['Store Number']

In [84]:
df_temp = pd.merge(df_store_county_ref,df[['Store Number', 'County Number']],how='inner', on='Store Number')

In [85]:
df_temp

        Store Number  County Number
0               3717            9.0
1               3717            9.0
2               3717            9.0
3               3717            9.0
4               3717            9.0
5               3717            9.0
6               3717            9.0
7               3717            9.0
8               3717            9.0
9               3717            9.0
10              3717            9.0
11              3717            9.0
12              3717            9.0
13              3717            9.0
14              3717            9.0
15              3717            9.0
16              3717            9.0
17              3717            9.0
18              3717            9.0
19              3717            9.0
20              3717            9.0
21              3717            9.0
22              3717            9.0
23              3717            9.0
24              3717            9.0
25              3717            9.0
26              3717            9.0
27              3717            9.0
28              3717            9.0
29              3717            9.0
...              ...            ...
270925          4985           75.0
270926          4985           75.0
270927          4737           11.0
270928          4737           11.0
270929          4737           11.0
270930          4737           11.0
270931          4776           14.0
270932          4776           14.0
270933          4338           64.0
270934          4338           64.0
270935          4338           64.0
270936          4338           64.0
270937          4338           64.0
270938          4338           64.0
270939          9023           14.0
270940          9018           31.0
270941          5216            NaN
270942          5216            NaN
270943          5216            NaN
270944          5237            NaN
270945          5237            NaN
270946          5237            NaN
270947          5237            NaN
270948          5237            NaN
270949          5237            NaN
270950          5201           31.0
270951          5201           31.0
270952          5201           31.0
270953          4778           11.0
270954          4778           11.0

[270955 rows x 2 columns]

In [ ]:
df.ix[df['County Number'].isnull(), 'County Number'] =

In [28]:
df[df['Store Number']==5210]

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
2549,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1022100.0,TEQUILA,35,89099,Cazadores Anejo,750,23.33,35.00,1,35.00,0.75
2678,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,65,10627,Canadian Club Whisky,1000,9.71,14.57,12,174.84,12.00
15946,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,65,24456,Kessler Blend Whiskey,750,5.51,8.27,12,99.24,9.00
18468,2016-03-15,5210,CLARINDA,51632,NaN,NaN,1031200.0,VODKA FLAVORED,380,41693,Uv Blue (raspberry) Vodka,750,6.50,9.75,12,117.00,9.00
24024,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1062300.0,FLAVORED RUM,65,44456,Cruzan Raspberry Rum,750,6.83,10.25,2,20.50,1.50
26752,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,260,37997,Smirnoff Vodka 80 Prf,1000,9.25,13.88,12,166.56,12.00
27605,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1062300.0,FLAVORED RUM,370,42716,Malibu Coconut Rum,750,7.49,11.24,12,134.88,9.00
30119,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,65,24458,Kessler Blend Whiskey,1750,11.02,16.53,6,99.18,10.50
35051,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1041100.0,AMERICAN DRY GINS,434,31657,Paramount Gin,1000,4.30,6.45,12,77.40,12.00
35250,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1012300.0,IRISH WHISKIES,370,15626,Jameson,750,14.99,22.49,3,67.47,2.25
37039,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1081200.0,CREAM LIQUEURS,260,74086,Godiva Liqueur,750,17.00,25.50,1,25.50,0.75
38373,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1062310.0,SPICED RUM,259,43028,Admiral Nelson Spiced Rum,1750,11.55,17.33,6,103.98,10.50
39218,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1082900.0,MISC. IMPORTED CORDIALS & LIQUEURS,192,65257,Jagermeister Liqueur,1000,15.54,23.31,12,279.72,12.00
42789,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,65,27410,Jim Beam Honey,750,10.49,15.74,3,47.22,2.25
45313,2016-03-08,5210,CLARINDA,51632,NaN,NaN,1011300.0,TENNESSEE WHISKIES,85,26824,Jack Daniels Old #7 Black Lbl Square,375,6.77,10.16,6,60.96,2.25
45611,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1081330.0,PEACH SCHNAPPS,65,82847,Dekuyper Peachtree,1000,7.87,11.81,12,141.72,12.00
47393,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,65,10626,Canadian Club Whisky,750,7.88,11.82,12,141.84,9.00
54397,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1081030.0,COFFEE LIQUEURS,370,67527,Kahlua Coffee Liqueur,1000,15.49,23.24,3,69.72,3.00
54476,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,55,35314,Barton Vodka,375,1.71,2.57,24,61.68,9.00
58905,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10807,Crown Royal Regal Apple,750,15.00,22.50,12,270.00,9.00
59648,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10834,Crown Royal Black,375,8.25,12.38,2,24.76,0.75
63534,2016-03-01,5210,CLARINDA,51632,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,421,69657,Dr. Mcgillicuddy's Mentholmint,1000,11.00,16.50,2,33.00,2.00
64102,2016-03-08,5210,CLARINDA,51632,NaN,NaN,1051110.0,BLACKBERRY BRANDIES,434,55084,Paramount Blackberry Brandy,375,3.55,5.33,6,31.98,2.25
73790,2016-02-09,5210,CLARINDA,51632,NaN,NaN,1022100.0,TEQUILA,395,87408,Jose Cuervo Especial Silver,750,10.49,15.74,12,188.88,9.00
74768,2016-03-15,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,11296,Crown Royal,750,15.00,22.50,12,270.00,9.00
87853,2016-01-26,5210,CLARINDA,51632,NaN,NaN,1032200.0,IMPORTED VODKA - MISC,370,34116,Absolut Mandrin,750,11.49,17.24,2,34.48,1.50
89373,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1071100.0,AMERICAN COCKTAILS,434,63530,Salvador's Original Margarita PET,1750,6.00,9.00,6,54.00,10.50
89506,2016-03-15,5210,CLARINDA,51632,NaN,NaN,1012300.0,IRISH WHISKIES,370,15628,Jameson,1750,29.98,44.97,6,269.82,10.50
90142,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10808,Crown Royal Regal Apple,1000,18.50,27.75,12,333.00,12.00
92773,2016-03-01,5210,CLARINDA,51632,NaN,NaN,1031200.0,VODKA FLAVORED,380,40632,UV Whipped,750,6.50,9.75,2,19.50,1.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170303,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1062310.0,SPICED RUM,260,43337,Captain Morgan Spiced Rum,1000,11.75,17.63,12,211.56,12.00
170484,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1062310.0,SPICED RUM,35,43205,Bacardi Oakheart,750,7.50,11.25,1,11.25,0.75
170524,2016-01-19,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,115,11774,Black Velvet,375,3.07,4.61,24,110.64,9.00
172881,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1081600.0,WHISKEY LIQUEUR,260,67264,Yukon Jack Canadian Liqueur,375,5.25,7.88,6,47.28,2.25
173820,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10803,Crown Royal Regal Apple Mini,300,7.35,11.03,1,11.03,0.30
176063,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,65,20247,Old Crow,1000,5.77,8.66,12,103.92,12.00
176446,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1082100.0,NaN,130,64136,Disaronno Amaretto,750,13.86,20.79,2,41.58,1.50
177824,2016-01-12,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,10805,Crown Royal Regal Apple,375,7.75,11.63,4,46.52,1.50
182336,2016-02-02,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,85,12467,Canadian Mist Whisky,1000,7.22,10.83,4,43.32,4.00
184387,2016-03-08,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,421,36978,Nikolai Vodka,1750,6.92,10.38,6,62.28,10.50
185540,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1081300.0,PEPPERMINT SCHNAPPS,322,75214,Kinky Blue,750,10.00,15.00,2,30.00,1.50
194241,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,297,23828,Five Star,1750,7.46,11.19,6,67.14,10.50
199501,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1012200.0,SCOTCH WHISKIES,55,8827,Lauder's,1000,6.14,9.21,3,27.63,3.00
206577,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1081600.0,WHISKEY LIQUEUR,421,64865,Fireball Cinnamon Whiskey PET,750,8.98,13.47,12,161.64,9.00
210270,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,260,65066,Goldschlager Cinnamon Schnapps,750,13.00,19.50,2,39.00,1.50
211792,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1022100.0,TEQUILA,410,88296,Patron Tequila Silver,750,27.00,40.50,2,81.00,1.50
213532,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1081010.0,AMERICAN AMARETTO,55,73986,Di Amore Amaretto,750,6.00,9.00,3,27.00,2.25
218033,2016-03-15,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,260,37417,Popov Vodka 80 Prf,1000,5.50,8.25,12,99.00,12.00
224610,2016-01-26,5210,CLARINDA,51632,NaN,NaN,1081230.0,WHITE CREME DE CACAO,434,78866,Paramount Creme De Cacao/white,750,4.75,7.13,3,21.39,2.25
230854,2016-02-23,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,260,25608,Seagrams 7 Crown Bl Whiskey,1750,11.96,17.94,6,107.64,10.50
230942,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,421,16517,Ancient Age Bourbon,1000,7.50,11.25,12,135.00,12.00
233303,2016-01-12,5210,CLARINDA,51632,NaN,NaN,1082900.0,MISC. IMPORTED CORDIALS & LIQUEURS,192,65257,Jagermeister Liqueur,1000,15.54,23.31,3,69.93,3.00
241865,2016-02-09,5210,CLARINDA,51632,NaN,NaN,1081300.0,PEPPERMINT SCHNAPPS,322,75214,Kinky Blue,750,10.00,15.00,2,30.00,1.50
244525,2016-03-08,5210,CLARINDA,51632,NaN,NaN,1062310.0,SPICED RUM,259,43984,Admiral Nelson Cherry Spiced Rum,750,5.78,8.67,2,17.34,1.50
245114,2016-03-15,5210,CLARINDA,51632,NaN,NaN,1081300.0,PEPPERMINT SCHNAPPS,434,81206,Paramount Peppermint Schnapps,750,3.75,5.63,3,16.89,2.25
254994,2016-03-08,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,55,35318,Barton Vodka,1750,6.92,10.38,6,62.28,10.50
256883,2016-01-19,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,260,37426,Popov Vodka 80 Prf Traveler,750,4.50,6.75,12,81.00,9.00
257642,2016-02-16,5210,CLARINDA,51632,NaN,NaN,1031080.0,VODKA 80 PROOF,300,36908,Mccormick Vodka Pet,1750,7.47,11.21,6,67.26,10.50
263730,2016-01-05,5210,CLARINDA,51632,NaN,NaN,1011100.0,BLENDED WHISKIES,300,24728,"Mccormick Blend Whiskey, Pet",1750,7.67,11.51,6,69.06,10.50
269482,2016-03-01,5210,CLARINDA,51632,NaN,NaN,1012210.0,SINGLE MALT SCOTCH,260,5696,Oban Single Malt Scotch,750,40.50,60.75,1,60.75,0.75

In [29]:
df['County Number'].value_counts()

77.0    49102
57.0    23511
82.0    16678
7.0     15083
52.0    13189
78.0     9111
85.0     8959
97.0     8562
31.0     7757
17.0     6374
29.0     4090
70.0     3983
23.0     3576
90.0     3529
30.0     3413
56.0     3324
94.0     3154
64.0     2996
50.0     2834
11.0     2748
25.0     2708
63.0     2603
91.0     2465
9.0      2243
8.0      2110
79.0     2089
21.0     1917
14.0     1915
53.0     1874
71.0     1720
        ...
37.0      677
99.0      672
83.0      663
47.0      634
45.0      607
46.0      588
1.0       585
38.0      566
76.0      525
65.0      508
58.0      484
59.0      476
19.0      464
39.0      438
13.0      424
12.0      402
98.0      388
41.0      363
68.0      353
72.0      352
54.0      344
87.0      298
89.0      245
2.0       234
5.0       227
27.0      224
26.0      203
80.0      202
93.0      160
36.0       27
Name: County Number, dtype: int64

In [ ]:
# Convert dates

In [ ]:
# Drop or replace bad values

# Convert integers

## Filter the Data

Some stores may have opened or closed in 2015. These data points will heavily skew our models, so we need to filter them out or find a way to deal with them.

You'll need to provide a summary in your project report about these data points. You may also consider using the monthly sales in your model and including other information (number of months or days each store is open) in your data to handle these unusual cases.

Let's record the first and last sales dates for each store. We'll save this information for later when we fit our models.

In [ ]:
# Determine which stores were open all of 2015
# Find the first and last sales date.



# Filter out stores that opened or closed throughout the year
# You may want to save this step until you start modelling

In [30]:
df['Date'].describe()

count                  270955
unique                    274
top       2015-12-01 00:00:00
freq                     1555
first     2015-01-05 00:00:00
last      2016-03-31 00:00:00
Name: Date, dtype: object

In [31]:
df['Date'].min()

Timestamp('2015-01-05 00:00:00')

In [39]:
store_min = df.groupby('Store Number')[['Date']].min()
store_max = df.groupby('Store Number')[['Date']].max()

In [55]:
store_date = pd.merge(df.groupby('Store Number')[['Date']].min(),df.groupby('Store Number')[['Date']].max(), how='outer', left_index=True, right_index=True)

In [57]:
store_date.columns = ['first_date', 'last_date']

In [48]:
start_time = pd.Timestamp('20150101')
end_time = pd.Timestamp('20151231')

In [59]:
store_date[(store_date['first_date']>=start_time) & (store_date['first_date']<=end_time) & (store_date['last_date']>=start_time) & (store_date['last_date']<=end_time)]

             first_date  last_date
Store Number
2205         2015-01-06 2015-12-28
2367         2015-01-06 2015-06-09
2487         2015-01-05 2015-11-02
2599         2015-01-05 2015-01-14
2951         2015-01-08 2015-01-29
2953         2015-01-08 2015-03-26
2954         2015-01-08 2015-03-26
2955         2015-01-08 2015-03-26
2956         2015-01-08 2015-03-25
2958         2015-01-05 2015-02-05
2959         2015-01-05 2015-03-25
2961         2015-01-08 2015-01-29
2962         2015-01-05 2015-03-26
2963         2015-01-05 2015-03-19
3437         2015-01-08 2015-12-30
3440         2015-01-08 2015-04-08
3451         2015-01-08 2015-02-26
3529         2015-01-06 2015-04-14
3631         2015-01-05 2015-08-24
3692         2015-01-08 2015-01-29
3761         2015-01-06 2015-03-24
3864         2015-01-13 2015-09-02
3925         2015-01-07 2015-02-25
3969         2015-01-06 2015-03-12
3970         2015-01-07 2015-12-29
3973         2015-01-13 2015-11-12
4012         2015-01-07 2015-04-01
4030         2015-01-06 2015-03-17
4059         2015-01-06 2015-01-13
4071         2015-01-08 2015-05-14
...                 ...        ...
4834         2015-01-05 2015-07-13
4855         2015-02-23 2015-11-16
4860         2015-02-11 2015-12-02
4870         2015-01-05 2015-02-23
4881         2015-01-08 2015-11-24
4889         2015-01-08 2015-04-09
4920         2015-01-06 2015-08-04
4939         2015-01-08 2015-01-08
4954         2015-02-24 2015-07-28
4990         2015-01-06 2015-03-10
5008         2015-01-06 2015-03-17
5026         2015-01-05 2015-05-11
5030         2015-01-08 2015-01-29
5032         2015-01-08 2015-07-13
5033         2015-01-06 2015-03-24
5036         2015-01-06 2015-05-19
5038         2015-01-08 2015-07-30
5053         2015-09-09 2015-09-09
5056         2015-07-06 2015-07-06
5084         2015-02-17 2015-06-23
5085         2015-01-06 2015-01-06
5093         2015-01-22 2015-12-23
5136         2015-05-04 2015-06-04
5139         2015-05-07 2015-11-05
5156         2015-08-06 2015-11-19
5161         2015-06-22 2015-10-05
5168         2015-07-21 2015-12-08
5193         2015-12-22 2015-12-22
5201         2015-12-01 2015-12-01
9018         2015-10-27 2015-10-27

[91 rows x 2 columns]

## Compute New Columns and Tables

Since we're trying to predict sales and/or profits, we'll want to compute some intermediate data. There are a lot of ways to do thisand good use of pandas is crucial. For example, for each transaction we may want to know:
* margin, retail cost minus bottle cost
* price per bottle
* price per liter

We'll need to make a new dataframe that indexes quantities by store:
* sales per store for all of 2015
* sales per store for Q1 2015
* sales per store for Q1 2016
* total volumes sold
* mean transaction revenue, gross margin, price per bottle, price per liter, etc.
* average sales per day
* number of days open

Make sure to retain other variables that we'll want to use to build our models, such as zip code, county number, city, etc. We recommend that you spend some time thinking about the model you may want to fit and computing enough of the suggested quantities to give you a few options.

Bonus tasks:
* Restrict your attention to stores that were open for all of 2015 and Q1 2016. Stores that opened or closed in 2015 will introduce outliers into your data.
* For each transaction we have the item category. You may be able to determine the store type (primarily wine, liquor, all types of alcohol, etc.) by the most common transaction category for each store. This could be a useful categorical variable for modelling.

In [ ]:
# Margin and Price per liter

In [ ]:
# Sales per store, 2015

# Filter by our start and end dates
df.sort_values(by=["Store Number", "Date"], inplace=True)
start_date = pd.Timestamp("20150101")
end_date = pd.Timestamp("20151231")
mask = (df['Date'] >= start_date) & (df['Date'] <= end_date)
sales = df[mask]

# Group by store name
sales = sales.groupby(by=["Store Number"], as_index=False)
# Compute sums, means
sales = sales.agg({"Sale (Dollars)": [np.sum, np.mean],
                   "Volume Sold (Liters)": [np.sum, np.mean],
                   "Margin": np.mean,
                   "Price per Liter": np.mean,
                   "Zip Code": lambda x: x.iloc[0], # just extract once, should be the same
                   "City": lambda x: x.iloc[0],
                   "County Number": lambda x: x.iloc[0]})
# Collapse the column indices
sales.columns = [' '.join(col).strip() for col in sales.columns.values]
# Rename columns

# Quick check
sales.head()

In [ ]:
# Q1 sales, may want to also use aggregate as above to have more columns (means, etc.)

# Sales 2015  Q1

# Sales 2016 Q1

Proceed with any calculations that you need for your models, such as grouping
sales by zip code, most common vendor number per store, etc. Once you have finished adding columns, be sure to save the dataframe.

In [ ]:
# Compute more things
# ...

In [ ]:
# Save this dataframe

# Let's add the dates computed above to this data.
sales["First Date"] = dates['Date amin']
sales["Last Date"] = dates['Date amax']

sales.to_csv("sales.csv")